### ISSUE TITLE
Investigate occasional slow queries between the envoy and Thanos querier in the harbor workload cluster

### ISSUE THREAD

**Issue by chess-knight** [SovereignCloudStack/k8s-observability#32]
Check the setup of the Thanos ruler and the constant evaluation of a huge number of rules between the observer and workload cluster. - Where to evaluate rules?
Check the connection between the envoy as a querier's store and the querier/ingress in the workload cluster. - Maybe set up some timeouts? Or maybe misconfiguration?

Until this issue is resolved, we connected Thanos Querier directly to Thanos Querier in the workload cluster via the NodePort.
Workload values:
```yaml
thanos:
  query:
    serviceGrpc:
      type: NodePort
      nodePorts:
        grpc: "31050"
```
Observer values:
```yaml
thanos:
  query:
    stores:
    - dnssrv+_grpc._tcp.kube-prometheus-thanos-ruler
    - 213.131.230.86:31050
```
